mysite/home/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^bus/', include('busnetwork.urls')),
    url(r'^metro/', include('metronetwork.urls')),
    url(r'^$', views.homepage, name='homepage'),
]

mysite/metronetwork/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'queryroute/', views.get_metroroutequery, name='get_metroroutequery'),
    url(r'querymetro/', views.get_metroquery, name='get_metroquery'),
    url(r'init_database/', views.initialize_metro_database, name='initialize_metro_database'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/metronetwork/models.py
from django.db import models
from django_mysql.models import ListCharField, ListTextField

# Create your models here.
class Metro(models.Model):
    color = models.CharField(max_length=100, primary_key=True)
    start_metrostation = models.CharField(max_length=100)
    end_metrostation = models.CharField(max_length=100)
    stations = ListCharField(base_field=models.CharField(max_length=100), size=1000, max_length=1000*101)
    distance = ListTextField(base_field=models.IntegerField(), size=1000)


class Graph(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    adj_List = ListCharField(base_field=models.CharField(max_length=100), size=1000, max_length=1000*101)
    dist_List = ListTextField(base_field=models.IntegerField(), size=100)

mysite/metronetwork/forms.py
from django import forms

class MetroRouteForm(forms.Form):
    uinpsrc = forms.CharField(label="Source Metro Station ", max_length=100)
    uinpdest = forms.CharField(label="Destination Metro Station ", max_length=100)

class MetroForm(forms.Form):
    uinpmetro = forms.CharField(label="Enter Metro Line Colour ", max_length=100)

mysite/metronetwork/views.py
from django.shortcuts import render
from .forms import MetroRouteForm, MetroForm
from .metro_route_algorithm import main_route
from .metro_details_algorithm import main_metro
from .modelsUtil.buildgraph import main1
from .calculate_metrofare import sunday_token, sunday_card, otherday_token, otherday_peakcard,otherday_nonpeakcard


def get_metroroutequery(request):
    if request.method=='POST':  #if post meathod process form data.
        form = MetroRouteForm(request.POST)
        if form.is_valid():
            uinpsrc = form.cleaned_data.get("uinpsrc").upper()
            uinpdest = form.cleaned_data.get("uinpdest").upper()
            retval = main_route(uinpsrc, uinpdest)
            distance = retval[-1][0]
            retval = retval[0:len(retval)-1]
            travelcost = {}
            travelcost['sun_card'] = sunday_card(float(distance))
            travelcost['sun_token'] = sunday_token(float(distance))
            travelcost['other_peakcard'] = otherday_peakcard(float(distance))
            travelcost['other_nonpeakcard'] = otherday_nonpeakcard(float(distance))
            travelcost['other_token'] = otherday_token(float(distance))
            blank_form = MetroRouteForm()
            context = {'srcstation': uinpsrc, 'deststation': uinpdest, 'allRoutes': retval, 'cost': travelcost, 'form': blank_form}
            return render(request, 'metronetwork/display_metroroute.html', context)
        else:
            context = {}
            return render(request, 'metronetwork/wrong_input.html', context)
    else:   #if get method, create a blank form.
        blank_form = MetroRouteForm()
        context = {'form': blank_form}
        return render(request, 'metronetwork/metroroute_query.html', context)


def get_metroquery(request):
    if request.method=='POST':  #if post meathod process form data.
        form = MetroForm(request.POST)
        if form.is_valid():
            uinpmetro = form.cleaned_data.get("uinpmetro").upper()
            retval = main_metro(uinpmetro)
            blank_form = MetroForm()
            context = {'metroDetails': retval, 'form': blank_form}
            return render(request, 'metronetwork/display_metro.html', context)
        else:
            context = {}
            return render(request, 'metronetwork/wrong_input.html', context)
    else:   #if get method, create a blank form.
        blank_form = MetroForm()
        context = {'form': blank_form}
        return render(request, 'metronetwork/metro_query.html', context)


def initialize_metro_database(request):    #To fill database automatically.
    main1()
    context = {}
    return render(request, 'metronetwork/init_complete.html', context)

mysite/metronetwork/templates/metronetwork/display_metro.html
{% extends 'home/base_header_and_navbar.html' %}
{% block body %}
<body>
    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
    <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
  crossorigin="anonymous"></script>
    <div class="container-fluid">
        <form method="post">
            {% csrf_token %}
            <div class="row row-buffer">
                <div class="col-sm-6" style=" margin: auto; margin-left: 50px; padding: 10px;">
                    <h4>{{ form }}</h4>
                </div>
                <div class="col-sm-3" style="margin: auto; padding: 10px;">
                    <button type="submit" class="btn btn-info btn-block" onClick="location.href='{% url 'get_metroquery' %}'">Get</button>
                </div>
            </div>
        </form>
        <div class="row row-buffer">
            <div class="col-sm-3" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h4><b>Metro Line:</b> {{ metroDetails.metro_color }}</h4>
            </div>
            <div class="col-sm-3" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h4><b>Start Station:</b> {{ metroDetails.start_station }}</h4>
            </div>
            <div class="col-sm-3" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h4><b>Dest. Station:</b> {{ metroDetails.end_station }}</h4>
            </div>
        </div>
        <hr style="height: 1px; background: #333; background-image: linear-gradient(to right, #ccc, #333, #ccc);">
        <div class="row row-buffer">
            <div class="col-sm-3" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h2>All Metro Stations:</h2>
            </div>
            <div class="col-sm-8" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h4 style="line-height: 40px;">
                    {% for stp in metroDetails.all_stations %}
                        {{ stp }}&nbsp;&nbsp;&rarr;&nbsp;&nbsp;
                    {% endfor %}
                    END
                </h4>
                <h4 style="line-height: 40px;">
                    {% if metroDetails.sub_stations1 %}
                        {% for stp in metroDetails.sub_stations1 %}
                            {{ stp }}&nbsp;&nbsp;&rarr;&nbsp;&nbsp;
                        {% endfor %}
                        END
                    {% endif %}
                </h4>
                <h4 style="line-height: 40px;">
                    {% if metroDetails.sub_stations2 %}
                        {% for stp in metroDetails.sub_stations2 %}
                            {{ stp }}&nbsp;&nbsp;&rarr;&nbsp;&nbsp;
                        {% endfor %}
                        END
                    {% endif %}
                </h4>
            </div>
        </div>
        <hr style="height: 1px; background: #333; background-image: linear-gradient(to right, #ccc, #333, #ccc);">
    </div>
    <script>
        $('#id_uinpsrc').addAttribute
    </script>
</body>
{% endblock %}

mysite/metronetwork/templates/metronetwork/display_metroroute.html
{% extends 'home/base_header_and_navbar.html' %}
{% block body %}
<head>
    <style>
        td, tr, th
        {
            border: 1px solid;
            text-align: center;
            padding: 10px;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <form method="post">
            {% csrf_token %}
            <div class="row row-buffer">
                <div class="col-sm-5" style=" margin: auto; margin-left: 20px; padding: 10px;">
                    <h4><label>Source Metro Station: </label>{{ form.uinpsrc }}</h4>
                </div>
                <div class="col-sm-5" style=" margin: auto; margin-left: 20px; padding: 10px;">
                    <h4><label>Dest. Metro Station: </label>{{ form.uinpdest }}</h4>
                </div>
                <div class="col-sm-1" style="margin: auto; padding: 10px;">
                    <button type="submit" class="btn btn-info btn-block" onClick="location.href='{% url 'get_metroroutequery' %}'">Find</button>
                </div>
            </div>
        </form>
        <div class="row row-buffer">
            <div class="col-sm-5" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h4><b>Start Metro Station:</b> {{ srcstation }}</h4>
            </div>
            <div class="col-sm-5" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h4><b>Dest. Metro Station:</b> {{ deststation }}</h4>
            </div>
        </div>
        <br><br>
        <table style="width:100%">
            <tr>
                <th>Type</th>
                <td>Sunday with Smart Card</td>
                <td>Sunday with Token</td>
                <td>Other days in Peak hours with Smart Card</td>
                <td>Other days in Non Peak hours with Smart Card</td>
                <td>Other days with Token</td>
            </tr>
            <tr>
                <th>Cost (Rupees)</th>
                <td>{{ cost.sun_card }}</td>
                <td>{{ cost.sun_token }}</td>
                <td>{{ cost.other_peakcard }}</td>
                <td>{{ cost.other_nonpeakcard }}</td>
                <td>{{ cost.other_token }}</td>
            </tr>
        </table>
        <br><br>
        <div class="row row-buffer">
            <div class="col-sm-3" style="margin: auto; margin-left: 50px; padding: 10px;">
                <h2>Best Routes: </h2>
            </div>
        </div>
        <div class="row row-buffer">
            <div class="col-sm-11" style="">
                {% for route in allRoutes %}
                    <h4 style="margin-left: 50px; line-height: 40px;">
                        {% for stop in route%}
                            {{ stop }}&nbsp;&nbsp;&rarr;&nbsp;&nbsp;
                        {% endfor %}
                        END
                        <hr style="height: 1px; background: #333; background-image: linear-gradient(to right, #ccc, #333, #ccc);">
                    </h4>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
{% endblock %}

mysite/metronetwork/templates/metronetwork/init_complete.html
{% extends 'home/base_header_and_navbar.html' %}
{% block body %}
<body>
    <h1>Initialization Complete.</h1>
</body>
{% endblock %}

mysite/metronetwork/templates/metronetwork/metro_query.html
{% extends 'home/base_header_and_navbar.html' %}
{% block body %}
<body>
    <div class="container-fluid">
        <form method="post">
            {% csrf_token %}
            <div class="row row-buffer">
                <div class="col-sm-6" style=" margin: auto; margin-left: 50px; padding: 10px;">
                    <h4>{{ form }}</h4>
                </div>
                <div class="col-sm-3" style="margin: auto; padding: 10px;">
                    <button type="submit" class="btn btn-info btn-block" onClick="location.href='{% url 'get_metroquery' %}'">Get</button>
                </div>
            </div>
        </form>
    </div>
</body>
{% endblock %}

mysite/metronetwork/templates/metronetwork/metroroute_query.html
{% extends 'home/base_header_and_navbar.html' %}
{% block body %}
<body>
    <div class="container-fluid">
        <form method="post">
            {% csrf_token %}
            <div class="row row-buffer">
                <div class="col-sm-5" style=" margin: auto; margin-left: 20px; padding: 10px;">
                    <h4><label>Start Metro Station: </label>{{ form.uinpsrc }}</h4>
                </div>
                <div class="col-sm-5" style=" margin: auto; margin-left: 20px; padding: 10px;">
                    <h4><label>Dest. Metro Station: </label>{{ form.uinpdest }}</h4>
                </div>
                <div class="col-sm-1" style="margin: auto; padding: 10px;">
                    <button type="submit" class="btn btn-info btn-block" onClick="location.href='{% url 'get_metroroutequery' %}'">Find</button>
                </div>
            </div>
        </form>
    </div>
</body>
{% endblock %}

mysite/metronetwork/templates/metronetwork/wrong_input.html
{% extends 'home/base_header_and_navbar.html' %}
{% block body %}
<body>
    <h1>Error.</h1>
</body>
{% endblock %}